name: Build & Push TrackMania Control (Github)

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-push.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'
  schedule:
    # rebuild les lundis à 1am UTC
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: downcase REPOSITORY_OWNER
        run: |
          echo "REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      - name: Get labels
        id: labels
        run: |
          DOCKER_IMAGE=ghcr.io/${{ env.REPOSITORY_OWNER }}/trackmaniacontrol
          VERSION=${{ github.ref }}
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "builddate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"
          echo "revision=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Login to Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ env.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push to Container Registry
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.labels.outputs.tags }}
          build-args: |
            VERSION=${{ steps.labels.outputs.version }}
            BUILD_DATE=${{ steps.labels.outputs.builddate }}
            REVISION=${{ steps.labels.outputs.revision }}